# Generated by Django 4.2.25 on 2025-12-09 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_club_banner_club_photo'),
        ('mysite', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='clubs.club'),
        ),
    ]
