# Generated by Django 4.2.26 on 2025-11-30 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('meeting_time', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('descriptions', models.CharField(blank=True, help_text='Enter one-word descriptions separated by commas', max_length=200)),
                ('leaders', models.ManyToManyField(blank=True, related_name='clubs_led', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
