# Generated by Django 4.2.26 on 2025-12-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_first_login_completed_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='3:00'),
        ),
    ]
