# Generated by Django 4.2.25 on 2025-12-08 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0004_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
