# Generated by Django 4.2.25 on 2025-12-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='club_banners/'),
        ),
        migrations.AddField(
            model_name='club',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='club_pics/'),
        ),
    ]
