# Generated by Django 4.2.26 on 2025-12-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_remove_event_day_remove_event_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
